### ISSUE TITLE
does not work with resourcepacks

### ISSUE THREAD

**Issue by RyanCR03** [xiaocihua/stack-to-nearby-chests#13]
when attempting to load a resourcepack, minecraft sends a 'resource reload failed' toast and does not load the pack and sends this error to the logs

```Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:88)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42)
	at net.minecraft.class_5944.modify$zoh000$fabric-rendering-v1$modifyProgramId(class_5944.java:654)
	at net.minecraft.class_5944.localvar$bkc000$optifabric$modifyProgramID(class_5944.java:2134)
	at net.minecraft.class_5944.<init>(class_5944.java:114)
	at net.minecraft.class_5944.<init>(class_5944.java:108)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28)
	at net.minecraft.class_757.mdf839eb$fabric-rendering-v1$lambda$registerShaders$0$0(class_757.java:2627)
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.lambda$register$1(LibGuiShaders.java:18)
	at net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback.lambda$static$0(CoreShaderRegistrationCallback.java:44)
	at net.minecraft.class_757.handler$zof000$fabric-rendering-v1$registerShaders(class_757.java:2630)
	at net.minecraft.class_757.method_34538(class_757.java:536)
	at net.minecraft.class_757$1.method_45777(class_757.java:460)
	at net.minecraft.class_757$1.method_18788(class_757.java:432)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more

**Comment by RyanCR03** [comment]
https://www.curseforge.com/minecraft/texture-packs/default-redone my personal resourcepack

**Comment by xiaocihua** [comment]
I tested it and didn't encounter the problem you mentioned. What other mods do you have installed?

**Comment by RyanCR03** [comment]
oddly enough, i removed all other mods and it still happened. i'm not sure why this happens for me.

**Comment by xiaocihua** [comment]
From the stack trace I found out that you have optifabric installed, so I tested it and this problem occurred. This may be caused by [LibGui](https://github.com/CottonMC/LibGui)(A GUI library used by this mod).
