### ISSUE TITLE
Crash with Smooth Swapping

### ISSUE THREAD

**Issue by PieKing1215** [xiaocihua/stack-to-nearby-chests#5]
Using quick stack to nearby chests crashes the game with the [Smooth Swapping](https://modrinth.com/mod/smooth-swapping) mod enabled.
Tested in singleplayer and with a bunch of other qol mods. Disabling Smooth Swapping fixes the issue but I can test with fewer other mods if you can't reproduce.
(This could be an issue on their side but it's not immediately clear to me which mod's fault it is)

<details>
<summary>stacktrace</summary>

```
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:938) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) ~[NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 46 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.getChangedStacks(class_465.java:3801) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.handler$cfo001$onRender(class_465.java:3763) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:929) ~[client-intermediary.jar:?]
```
</details>

**Comment by xiaocihua** [comment]
I released [a modified version of Smooth Swapping](https://github.com/xiaocihua/Smooth-Swapping/releases/tag/0.6.2) that should work fine with this mod. I'm still looking for a better solution.

**Comment by xiaocihua** [comment]
Smooth Swapping mod after 0.8.1 no longer conflicts with this mod.
